### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by Harfho** [nazavod777/invisible_captcha_bypasser#1]
Traceback (most recent call last):
  File "c:/Users/Harfho/Desktop/2captcha/invisible_captha_solver .py", line 3, in <module>
    from invisible_captcha_bypasser import solve_captcha
  File "C:\Users\Harfho\.virtualenvs\2captcha-pdOmf8X4\lib\site-packages\invisible_captcha_bypasser\__init__.py", line 1, in <module>
    from .captcha_solver import solve_captcha
  File "C:\Users\Harfho\.virtualenvs\2captcha-pdOmf8X4\lib\site-packages\invisible_captcha_bypasser\captcha_solver.py", line 3, in <module>
    from better_proxy import Proxy
  File "C:\Users\Harfho\.virtualenvs\2captcha-pdOmf8X4\lib\site-packages\better_proxy\__init__.py", line 1, in <module>
    from .proxy import Proxy
  File "C:\Users\Harfho\.virtualenvs\2captcha-pdOmf8X4\lib\site-packages\better_proxy\proxy.py", line 16, in <module>
    def _load_lines(filepath: Path | str) -> list[str]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by nazavod777** [comment]
use python 3.11.6 +
